[package]
name = "repowiki-wiki"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true

[dependencies]
repowiki-core = { workspace = true }
repowiki-graph = { workspace = true }
regex = { workspace = true }
